version: "3"
services:
  front:
    build:
      context: ./Rental_Book_Frontend
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-networks
    volumes:
      - ./Rental_Book_Frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./Rental book API
      dockerfile: Dockerfile
    container_name: api-container
    networks:
      - mern-stack-networks
    ports:
      - "5000:5000"
    volumes:
      - ./Rental book API:/app
    env_file:
      - ./Rental book API/config.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - mern-stack-networks
    volumes:
      - mongoData:/data/db

networks:
  mern-stack-networks:
volumes:
  mongoData:
