version: "3"
services:
  database:
    image: mongo
    container_name: mongo-db
    port:
      - "27017:27017"
    volumes:
      - db-data:/data/db
   
   backend:
    build: ./Rental book API
    container_name: node-api
    restart: always
    port:
      - "5000:5000"
    depends_on:
      - database
   
  frontend:
    build: ./Rental_Book_Frontend
    container_name: react-ui
    port:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    
 

